"""MC-KOS-43: Render Markdown report from evidence pack JSON.

Usage:
    from kosniper.export.report_md import render_report
    md_text = render_report(evidence_pack_dict)
"""

from __future__ import annotations

from typing import Any, Dict, List


def render_report(pack: Dict[str, Any]) -> str:
    """Render a concise Markdown report from an evidence pack dict.

    Args:
        pack: Parsed JSON dict from scan output (evidence pack format).

    Returns:
        Markdown string suitable for writing to report.md.

    Contract:
        - Never implies GREEN when overall_verdict is ABSTAIN or empty checks.
        - Renders without crashing even when checks list is empty.
    """
    lines: List[str] = []

    # Header
    lines.append("# KOSniper Report")
    lines.append("")

    # Overall verdict (uppercase for emphasis)
    overall = pack.get("overall_verdict") or pack.get("verdict") or "unknown"
    lines.append(f"**Overall Verdict:** {str(overall).upper()}")
    lines.append("")

    # Summary
    summary = pack.get("summary", "")
    if summary:
        lines.append(f"**Summary:** {summary}")
        lines.append("")

    # Checks section
    checks = pack.get("checks", [])
    lines.append("## Checks")
    lines.append("")

    if not checks:
        # Explicit note when no checks (ABSTAIN case) - never imply GREEN
        lines.append("_No checks produced findings. Manual review required._")
        lines.append("")
    else:
        for check in checks:
            check_id = check.get("check_id", "UnknownChecker")
            verdict = check.get("verdict", "unknown")
            reason = check.get("reason", "")

            lines.append(f"### {check_id}")
            lines.append("")
            lines.append(f"- **Verdict:** {verdict}")
            if reason:
                lines.append(f"- **Reason:** {reason}")

            # Evidence list
            evidence = check.get("evidence", [])
            if evidence:
                lines.append("- **Evidence:**")
                for ev in evidence:
                    ev_line = _format_evidence(ev)
                    lines.append(f"  - {ev_line}")
            lines.append("")

    # Document provenance section
    doc_map = pack.get("document_map")
    if doc_map:
        lines.append("## Document Provenance")
        lines.append("")
        doc_id = doc_map.get("doc_id", "unknown")
        lines.append(f"- **Document:** {doc_id}")
        offset_basis = doc_map.get("offset_basis")
        if offset_basis:
            lines.append(f"- **Offset Basis:** {offset_basis}")
        sha256 = doc_map.get("overall_sha256")
        if sha256:
            lines.append(f"- **SHA256:** `{sha256}`")
        page_count = len(doc_map.get("pages", []))
        lines.append(f"- **Pages:** {page_count}")
        lines.append("")

    # Footer with schema version
    schema_version = pack.get("schema_version", "unknown")
    lines.append("---")
    lines.append(f"_Generated by KOSniper (schema {schema_version})_")
    lines.append("")

    return "\n".join(lines)


def _format_evidence(ev: Dict[str, Any]) -> str:
    """Format a single evidence item as a compact string."""
    doc_id = ev.get("doc_id", "")
    page = ev.get("page", "?")
    snippet = ev.get("snippet") or ""

    # Truncate long snippets for readability
    if len(snippet) > 80:
        snippet = snippet[:77] + "..."

    # Location prefix
    loc = f"[{doc_id}:{page}]" if doc_id else f"[page {page}]"

    # Build line
    parts = [loc, f'"{snippet}"']

    # Add offsets if present
    start = ev.get("start_offset")
    end = ev.get("end_offset")
    if start is not None and end is not None:
        parts.append(f"(offsets: {start}-{end})")

    return " ".join(parts)
